"""baseline

Revision ID: 17da225cf72e
Revises: 
Create Date: 2026-08-08 12:04:00.151786
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '17da225cf72e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_refreshes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seen', sa.Integer(), nullable=False),
    sa.Column('added', sa.Integer(), nullable=False),
    sa.Column('per_indexer', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('mtime', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('container', sa.String(), nullable=True),
    sa.Column('video_codec', sa.String(), nullable=True),
    sa.Column('audio_codec', sa.String(), nullable=True),
    sa.Column('audio_channels', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('subtitle_streams', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('playback_strategy', sa.String(), nullable=False),
    sa.Column('probed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_files_path'), 'media_files', ['path'], unique=True)
    op.create_table('catalog_works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('normalised_title', sa.String(length=512), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('display_title', sa.String(length=512), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=True),
    sa.Column('provider_id', sa.String(length=64), nullable=True),
    sa.Column('overview', sa.String(), nullable=True),
    sa.Column('poster_url', sa.String(length=512), nullable=True),
    sa.Column('backdrop_url', sa.String(length=512), nullable=True),
    sa.Column('genres', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('best_seeder_pct', sa.Float(), nullable=False),
    sa.Column('release_count', sa.Integer(), nullable=False),
    sa.Column('latest_release_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('library_file_id', sa.Integer(), nullable=True),
    sa.Column('download_job_id', sa.String(length=128), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['library_file_id'], ['media_files.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'normalised_title', 'year', name='uq_work_identity')
    )
    op.create_index(op.f('ix_catalog_works_kind'), 'catalog_works', ['kind'], unique=False)
    op.create_index('ix_works_kind_first_seen', 'catalog_works', ['kind', 'first_seen_at'], unique=False)
    op.create_index('ix_works_kind_latest', 'catalog_works', ['kind', 'latest_release_at'], unique=False)
    op.create_index('ix_works_kind_seeders', 'catalog_works', ['kind', 'best_seeder_pct'], unique=False)
    op.create_table('catalog_releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('info_hash', sa.String(length=40), nullable=False),
    sa.Column('indexer', sa.String(length=128), nullable=False),
    sa.Column('guid', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=True),
    sa.Column('parsed_title', sa.String(length=512), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('episode', sa.Integer(), nullable=True),
    sa.Column('episode_end', sa.Integer(), nullable=True),
    sa.Column('quality', sa.String(length=16), nullable=True),
    sa.Column('release_group', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('seeders', sa.Integer(), nullable=False),
    sa.Column('leechers', sa.Integer(), nullable=False),
    sa.Column('seeder_pct', sa.Float(), nullable=False),
    sa.Column('magnet', sa.Text(), nullable=True),
    sa.Column('download_url', sa.Text(), nullable=True),
    sa.Column('imdb_id', sa.String(length=16), nullable=True),
    sa.Column('categories', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('predicted_strategy', sa.String(length=24), nullable=False),
    sa.Column('missed_refreshes', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['work_id'], ['catalog_works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('info_hash', name='uq_release_identity')
    )
    op.create_index(op.f('ix_catalog_releases_kind'), 'catalog_releases', ['kind'], unique=False)
    op.create_index('ix_releases_work', 'catalog_releases', ['work_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_releases_work', table_name='catalog_releases')
    op.drop_index(op.f('ix_catalog_releases_kind'), table_name='catalog_releases')
    op.drop_table('catalog_releases')
    op.drop_index('ix_works_kind_seeders', table_name='catalog_works')
    op.drop_index('ix_works_kind_latest', table_name='catalog_works')
    op.drop_index('ix_works_kind_first_seen', table_name='catalog_works')
    op.drop_index(op.f('ix_catalog_works_kind'), table_name='catalog_works')
    op.drop_table('catalog_works')
    op.drop_index(op.f('ix_media_files_path'), table_name='media_files')
    op.drop_table('media_files')
    op.drop_table('jobs')
    op.drop_table('catalog_refreshes')
    # ### end Alembic commands ###
